Bump to version 0.4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -17,30 +17,29 @@
 #
 
 check_cmd() {
-	if ! command -v ${1} &> /dev/null
-	then
-		echo "not found!"
-		exit
+	cmd_path=$(command -v "${1}")
+	if [[ -z "${cmd_path}" ]]; then
+		echo " Command \"${1}\" not found!"
+		exit -1
 	else
-		echo `command -v ${1}`
+		echo "${cmd_path}"
 	fi
 }
 
-check() {
+check_cc_cpp_comp() {
 	printf "Checking for C compiler..."
 	if [[ -z "${CC}" ]]; then
-		CC=cc
+		CC="cc"
 	fi
 	check_cmd "${CC}"
 	printf "Checking for C++ compiler..."
 	if [[ -z "${CXX}" ]]; then
-		CXX=g++
+		CXX="c++"
 	fi
 	check_cmd "${CXX}"
 }
 
 check_lpf() {
-	check
 	printf "Checking for lpfcc..."
 	check_cmd "$1lpfcc"
 	printf "Checking for lpfcxx..."
@@ -49,150 +48,261 @@ check_lpf() {
 	check_cmd "$1lpfrun"
 }
 
+# validates the path and returns the absolute one WITHOUT trailing '/'
+validate_command_result() {
+	err_val=$1
+	error_msg=$2
+	if [[ "${err_val}" != "0" ]]; then
+		echo "${error_msg}"
+		echo
+		exit -1;
+	fi
+}
+
+print_help() {
+	echo "Usage: ./configure --prefix=<path> [--with-lpf[=<path>]]\
+ [--with-banshee=<path>] [--with-snitch=<path>] [--no-reference] [--debug-build] [--generator=<value>] [--show]"
+	echo " "
+	echo "Required arguments:"
+	echo "  --prefix=<path/to/install/directory/>"
+	echo " "
+	echo "Optional arguments:"
+	echo "  --with-lpf[=<path/to/lpf/install>]  - enable LPF backend, optionally specifying \
+the location where LPF is installed"
+	echo "  --with-banshee=<path/>              - path to the the tools to compile the banshee backend"
+	echo "  --with-snitch=<path/>               - path to the tools for Snitch support within the banshee backend"
+	echo "  --no-reference                      - disables the reference and reference_omp backends"
+	echo "  --debug-build                       - build the project with debug options (tests will run much slower!)"
+	echo "  --generator=<value>                 - set the generator for CMake (otherwise use CMake's default)"
+	echo "  --show                              - show generation commands instead of running them"
+	echo " "
+	echo "Notes:"
+	echo "  - If the install directory does not exist, it will be created."
+	echo "  - The --prefix path is mandatory. No make targets will execute"
+	echo "    without configuring this path first."
+	echo "  - This ./configure script is re-entrant and will simply overwrite"
+	echo "    *all* previous setting, but will not clean up anything. For best"
+	echo "    results, execute ./configure only once on a clean source directory."
+}
+
 reference=yes
 banshee=no
-lpf=yes
+lpf=no
 show=no
 FLAGS=$''
 LPF_INSTALL_PATH=
 BANSHEE_PATH=
 SNITCH_PATH=
+debug_build=no
+generator=
+
+if [[ "$#" -lt 1 ]]; then
+	echo "No argument given, at least --prefix=<path/to/install/directory/> is mandatory"
+	echo
+	print_help
+	exit 1
+fi
 
 for arg in "$@"
 do
 	case "$arg" in
-	-h|--help)	echo "Usage: ./configure --prefix=<path> [--with-lpf=<path>]\
- [--with-banshee=<path>] [--no-lpf] [--no-reference] [--no-banshee]"
-			echo " "
-			echo "Required arguments:"
-			echo "  --prefix=<path/to/install/directory/>"
-			echo " "
-			echo "Optional arguments:"
-			echo "  --with-lpf=<path/>             - where LPF is installed"
-			echo "  --no-reference                 - disables the reference and reference_omp backends"
-			echo "  --no-lpf                       - disables all backends that depend on LPF"
-			echo "  --no-banshee                   - disables the banshee backend"
-			echo "  --with-banshee=<path/>         - path to the the tools to compile the banshee backend"
-			echo "  --with-snitch=<path/>          - path to the tools for Snitch support within the banshee backend"
-			echo " "
-			echo "Notes:"
-			echo "  - If the install directory does not exist, it will be created."
-			echo "  - If --with-lpf is omitted, LPF is assumed to be in the system"
-			echo "    path."
-			echo "  - The --prefix path is mandatory. No make targets will execute"
-			echo "    without configuring this path first."
-			echo "  - This ./configure script is re-entrant and will simply overwrite"
-			echo "    *all* previous setting, but will not clean up anything. For best"
-		    echo "    results, execute ./configure only once on a clean source directory."
+	-h|--help)
+			print_help
 			exit
 			;;
-	--prefix=*)	prefix="`echo "${arg}" | cut -d'=' -f2-`"
+	--prefix=*)
+			prefix="${arg#--prefix=}"
 			;;
-	--with-lpf=*)
-			LPF_INSTALL_PATH="`echo "${arg}" | cut -d'=' -f2-`"
+	--with-lpf*)
+			suffix=${arg#--with-lpf}
+			if [[ -z "${suffix}" ]]; then
+				LPF_INSTALL_PATH=""
+			else
+				if [[ "${suffix:0:1}" != "=" ]]; then
+					echo "please, specify the LPF installation path with --with-lpf=</path/to/lpf/install>"
+					exit 1
+				fi
+				LPF_INSTALL_PATH="${suffix:1}"
+				if [[ -z "${LPF_INSTALL_PATH}" ]]; then
+					echo "please, specify a path after = (e.g. --with-lpf=</path/to/lpf/install>) \
+or assume default paths (--with-lpf)"
+				fi
+			fi
 			lpf=yes
 			;;
-	--no-lpf)
-			FLAGS+=$'NO_LPF=true\n'
-			lpf=no
-			;;
-	--no-banshee)
-			FLAGS+=$'NO_BANSHEE=true\n'
-			banshee=no
-			;;
 	--with-banshee=*)
-			BANSHEE_PATH="`echo "${arg}" | cut -d'=' -f2-`"
+			BANSHEE_PATH="${arg#--with-banshee=}"
 			banshee=yes
 			;;
 	--with-snitch=*)
-			SNITCH_PATH="`echo "${arg}" | cut -d'=' -f2-`"
+			SNITCH_PATH="${arg#--with-snitch=}"
 			banshee=yes
 			;;
 	--no-reference)
-			FLAGS+=$'NO_REFERENCE=true\n'
 			reference=no
+			;;
+	--debug-build)
+			debug_build=yes
+			;;
+	--generator=*)
+			generator="${arg#--generator=}"
 			;;
 	--show)
 			show=yes
 			;;
-	*)		echo "Warning: ignoring argument $arg".
+	*)
+			echo "Unknown argument ${arg}"
+			exit 1
+			;;
 	esac
 done
 
-if [ -z "${prefix}" ] || [ "${prefix}" = " " ]; then
-	echo "Error: empty install prefix (${prefix}). The --prefix=</install/path/> option is mandatory."
+# VALIDATE INPUTS
+
+if [[ -z "${prefix}" ]]; then
+	echo "Error: empty install prefix. The --prefix=</install/path/> option is mandatory."
 	exit 1;
 fi
 
-if [[ "${banshee}" != "no" ]]; then
-	if [[ -z "${BANSHEE_PATH}" || -z "${SNITCH_PATH}" ]]; then
-		echo "Error: please provide values to both '--with-banshee' and '--with-snitch' arguments"
-		exit 1
-	fi
-	if [[ ! -d "${BANSHEE_PATH}" ]]; then
-		echo "Error: ${BANSHEE_PATH} is not a valid path"
-		exit 1
-	fi
-	if [[ ! -d "${SNITCH_PATH}" ]]; then
-		echo "Error: ${SNITCH_PATH} is not a valid path"
-		exit 1
-	fi
-	# remove possible trailing '/'
-	BANSHEE_PATH=$(cd ${BANSHEE_PATH} && pwd)
-	SNITCH_PATH=$(cd ${SNITCH_PATH} && pwd)
-else
-	FLAGS+=$'NO_BANSHEE=true\n'
-	# blank the variables
-	BANSHEE_PATH=
-	SNITCH_PATH=
-fi
+echo
 
-if [ ! -d "${prefix}" ]; then
-	echo "Warning: install directory will be created when output is written there (either on \`make install' or on installing a pre-packaged dependency).";
-	DIRNAME=`dirname "${prefix}"`
-	if [ ! -d "${DIRNAME}" ]; then
-		echo "Error: parent directory of target installation path does not exist.";
-		exit 1;
-	fi
-	BASENAME=`basename "${prefix}"`
-	DIRNAME=`readlink -e ${DIRNAME}`
-	ABSOLUTE_PREFIX="${DIRNAME}/${BASENAME}"
+# ~ is a valid character in file names according to UNIX standard, but some shells
+# like Bash give it a special meaning and thus do the substitution ~ => $HOME
+# (unless wrapped by quotes), while realpath doesn't do it; however, Bash'
+# substitution excludes the usage of wrapping quotes, making Bash commands fool in
+# case of paths with spaces, which would look like different arguments; hence,
+# we do a manual substitution and then we call the various tools with wrapping
+# quotes to support spaces as well
+prefix="${prefix/#\~/$HOME}"
+parent_dir_relative=$(dirname "${prefix}")
+PARENT_DIR="$(realpath -e -q "${parent_dir_relative}")"
+validate_command_result "$?" "Parent directory path '${parent_dir_relative}' for --prefix \
+does not exist: please create it before invocation"
+BASENAME=`basename "${prefix}"`
+ABSOLUTE_PREFIX="${PARENT_DIR}/${BASENAME}"
+if [[ ! -d "${ABSOLUTE_PREFIX}" ]]; then
+	echo "Warning: install directory will be created when output is written there \
+(either on \`make install' or on installing a pre-packaged dependency)."
+	echo
 else
-	ABSOLUTE_PREFIX=`readlink -e ${prefix}`
 	echo "Warning: any pre-existing data in ${ABSOLUTE_PREFIX} may be overwritten."
+	echo
 fi
 
-if [ x$lpf = xno ]; then
-	check
-elif [ x$LPF_INSTALL_PATH = x ]; then
-	check_lpf
-else
-	if [ ! -d "${LPF_INSTALL_PATH}" ]; then
-		echo "Given LPF installation directory does not exist!"
-		exit;
+
+if [[ "${reference}" == "yes" || "${lpf}" == "yes" ]]; then
+	check_cc_cpp_comp
+fi
+
+if [[ "${lpf}" == "yes" ]]; then
+	if [[ -z "${LPF_INSTALL_PATH}" ]]; then
+		check_lpf
+		lpfrun_path=$(command -v lpfcc)
+		ABSOLUTE_LPF_INSTALL_PATH=$(dirname "${lpfrun_path}")
+	else
+		ABSOLUTE_LPF_INSTALL_PATH="$(realpath -e -q "${LPF_INSTALL_PATH/#\~/$HOME}")"
+		validate_command_result "$?" "LPF installation path '${LPF_INSTALL_PATH}' does not exist"
+		check_lpf "${ABSOLUTE_LPF_INSTALL_PATH}/bin/"
 	fi
-	check_lpf "${LPF_INSTALL_PATH}/bin/"
-	ABSOLUTE_LPF_INSTALL_PATH=`readlink -e ${LPF_INSTALL_PATH}`
 fi
 
-FLAGS+=CC=${CC}$'\n'
-FLAGS+=CXX=${CXX}$'\n'
 
-if [ x$show = xyes ]; then
+if [[ "${banshee}" == "yes" ]]; then
+	ABSOLUTE_BANSHEE_PATH="$(realpath -e -q "${BANSHEE_PATH/#\~/$HOME}")"
+	validate_command_result "$?" "Invalid Banshee installation path '${BANSHEE_PATH}', \
+please provide the path to the Banshee toolchain via --with-banshee=</path/to/banshee>"
+	ABSOLUTE_SNITCH_PATH="$(realpath -e -q "${SNITCH_PATH/#\~/$HOME}")"
+	validate_command_result "$?" "Invalid Snitch installation path '${SNITCH_PATH}', \
+please provide the path to the Snitch toolchain via --with-snitch=</path/to/snitch>"
+fi
+
+# CONFIGURE BUILDING INFRASTRUCTURE
+CURRENT_DIR="$(pwd)"
+
+if [[ "${reference}" == "yes" || "${lpf}" == "yes" ]];then
+	printf "Checking for cmake..."
+	check_cmd "cmake"
+
+	BUILD_DIR="${CURRENT_DIR}/build"
+	if [[ -d "${BUILD_DIR}" && "${show}" = "no" ]]; then
+		echo
+		echo "${BUILD_DIR} already exists: please, remove it to generate a new CMake build"
+		echo
+		exit -1
+	fi
 	echo
-	echo "flags.mk contents: ${FLAGS}"
-	echo "paths.mk contents:"
-	echo "GRB_INSTALL_PATH=${ABSOLUTE_PREFIX}"
-	echo "LPF_INSTALL_PATH=${ABSOLUTE_LPF_INSTALL_PATH}"
-	echo "BANSHEE_PATH=${BANSHEE_PATH}"
-	echo "SNITCH_PATH=${SNITCH_PATH}"
+	echo "*** CONFIGURING CMake inside ${BUILD_DIR} ***"
 	echo
-else
-	echo "${FLAGS}" > flags.mk
-	echo "GRB_INSTALL_PATH=${ABSOLUTE_PREFIX}" > paths.mk
-	echo "LPF_INSTALL_PATH=${ABSOLUTE_LPF_INSTALL_PATH}" >> paths.mk
-	echo "BANSHEE_PATH=${BANSHEE_PATH}" >> paths.mk
-	echo "SNITCH_PATH=${SNITCH_PATH}" >> paths.mk
+
+	CMAKE_OPTS="-DCMAKE_INSTALL_PREFIX='${ABSOLUTE_PREFIX}'"
+
+	if [[ "${debug_build}" == "yes" ]]; then
+		CMAKE_OPTS+=" -DCMAKE_BUILD_TYPE=Debug"
+	else
+		CMAKE_OPTS+=" -DCMAKE_BUILD_TYPE=Release"
+	fi
+
+	DATASETS_DIR="${CURRENT_DIR}/datasets"
+	if [[ -d "${DATASETS_DIR}" ]]; then
+		CMAKE_OPTS+=" -DDATASETS_DIR='${DATASETS_DIR}'"
+	fi
+	# GNN_DATASET_PATH is not needed, because unittests.sh sets a default
+
+	if [[ "${reference}" == "no" ]]; then
+		CMAKE_OPTS+=" -DWITH_REFERENCE_BACKEND=OFF -DWITH_OMP_BACKEND=OFF"
+	fi
+	if [[ "${lpf}" == "yes" ]]; then
+		CMAKE_OPTS+=" -DLPF_INSTALL_PATH='${ABSOLUTE_LPF_INSTALL_PATH}'"
+	fi
+
+	if [[ ! -z "${generator}" ]]; then
+		CMAKE_OPTS+=" -G '${generator}'"
+	fi
+
+	CONFIG_COMMAND="cd ${BUILD_DIR} && cmake ${CMAKE_OPTS} ../"
+	echo
+	if [[ "${show}" = "yes" ]]; then
+		echo "Configuration command:"
+		echo "${CONFIG_COMMAND}"
+	else
+		mkdir "${BUILD_DIR}"
+		bash -c "${CONFIG_COMMAND}"
+		if [[ $? -ne 0 ]]; then
+			echo "Error during generation of the CMake infrastructure"
+			echo
+			exit -1
+		fi
+		echo "*** you can build GraphBLAS inside ${BUILD_DIR} ***"
+	fi
+	echo
+fi
+
+if [[ "${banshee}" == "yes" ]]; then
+	echo
+	echo "************************* WARNING *************************"
+	echo "You have selected the Banshee backend, which uses Makefile"
+	echo "to build and may lag behind other ALP/GraphBLAS backends"
+	echo
+	echo "*** CONFIGURING Makefile inside ${CURRENT_DIR} ***"
+
+	if [[ "${show}" = "yes" ]]; then
+		echo
+		echo "paths.mk contents:"
+		echo "GRB_INSTALL_PATH=${ABSOLUTE_PREFIX}"
+		echo "LPF_INSTALL_PATH=${ABSOLUTE_LPF_INSTALL_PATH}"
+		echo "BANSHEE_PATH=${ABSOLUTE_BANSHEE_PATH}"
+		echo "SNITCH_PATH=${ABSOLUTE_SNITCH_PATH}"
+		echo
+	else
+		echo "GRB_INSTALL_PATH=${ABSOLUTE_PREFIX}" > paths.mk
+		echo "LPF_INSTALL_PATH=${ABSOLUTE_LPF_INSTALL_PATH}" >> paths.mk
+		echo "BANSHEE_PATH=${ABSOLUTE_BANSHEE_PATH}" >> paths.mk
+		echo "SNITCH_PATH=${ABSOLUTE_SNITCH_PATH}" >> paths.mk
+
+		echo
+		echo "*** you can build GraphBLAS here ***"
+		echo
+	fi
 fi
 
 echo "Configure done."
